controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Homepage
app_homepage:
    path: /
    controller: App\Controller\HomeController::index

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: [GET]

# Calendar
calendar:
    path: /calendar
    controller: App\Controller\CalendarController::index
    methods: [GET]

# Events
app_event_index:
    path: /event/
    controller: App\Controller\EventController::index
    methods: [GET]

app_event_new:
    path: /event/new
    controller: App\Controller\EventController::new
    methods: [GET, POST]

app_event_show:
    path: /event/{id}
    controller: App\Controller\EventController::show
    methods: [GET]

app_event_edit:
    path: /event/{id}/edit
    controller: App\Controller\EventController::edit
    methods: [GET, POST]

app_event_delete:
    path: /event/{id}
    controller: App\Controller\EventController::delete
    methods: [POST]

# User
user:
    path: /user/
    controller: App\Controller\UserController::index
edit_user:
    path: /user/edit
    controller: App\Controller\UserController::edit
change_password:
    path: /user/change-password
    controller: App\Controller\UserController::changePassword
change_email:
    path: /user/change-email
    controller: App\Controller\UserController::changeEmail

# Contacts
app_contact_index:
    path: /contact/
    controller: App\Controller\ContactController::index
    methods: [GET]

app_contact_new:
    path: /contact/new
    controller: App\Controller\ContactController::new
    methods: [GET, POST]

app_contact_show:
    path: /contact/{id}
    controller: App\Controller\ContactController::show
    methods: [GET]

app_contact_edit:
    path: /contact/{id}/edit
    controller: App\Controller\ContactController::edit
    methods: [GET, POST]

app_contact_delete:
    path: /contact/{id}
    controller: App\Controller\ContactController::delete
    methods: [POST]

# Messages
messages:
    path: /messages
    controller: App\Controller\MessageController::index
send_message:
    path: /messages/send
    controller: App\Controller\MessageController::send
