controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Homepage
app_homepage:
    path: /
    controller: App\Controller\HomeController::index

dashboard:
    path: /user/{id}/dashboard
    controller: App\Controller\DashboardController::index
    methods: [GET]

# Calendar
calendar:
    path: /calendar
    controller: App\Controller\CalendarController::index
    methods: [GET]

calendar_events:
    path: /calendar/events
    controller: App\Controller\CalendarController::events
    methods: [GET]

calendar_event_create:
    path: /calendar/event/create
    controller: App\Controller\CalendarController::create
    methods: [POST]

calendar_event_edit:
    path: /calendar/event/{id}/edit
    controller: App\Controller\CalendarController::edit
    methods: [POST]

calendar_event_delete:
    path: /calendar/event/{id}/delete
    controller: App\Controller\CalendarController::delete
    methods: [POST]

# User
user:
    path: /user/{id}
    controller: App\Controller\UserController::index
edit_user:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
change_password:
    path: /user/{id}/change-password
    controller: App\Controller\UserController::changePassword
change_email:
    path: /user/{id}/change-email
    controller: App\Controller\UserController::changeEmail

# Contacts
contacts:
    path: /contacts
    controller: App\Controller\ContactController::index
create_contact:
    path: /contacts/create
    controller: App\Controller\ContactController::create
edit_contact:
    path: /contacts/{id}/edit
    controller: App\Controller\ContactController::edit
delete_contact:
    path: /contacts/{id}/delete
    controller: App\Controller\ContactController::delete

# Messages
messages:
    path: /messages
    controller: App\Controller\MessageController::index
send_message:
    path: /messages/send
    controller: App\Controller\MessageController::send
