controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index
    methods: [GET]

# Homepage
app_homepage:
    path: /
    controller: App\Controller\HomeController::index


# User
user:
    path: /user
    controller: App\Controller\UserController::index
edit_user:
    path: /user/edit
    controller: App\Controller\UserController::edit
change_password:
    path: /user/change-password
    controller: App\Controller\UserController::changePassword
change_email:
    path: /user/change-email
    controller: App\Controller\UserController::changeEmail

# Dashboard

# Calendar
calendar_events:
    path: /calendar/events
    methods: [GET]
    controller: App\Controller\CalendarController::getEvents

calendar_event_create:
    path: /calendar/event/create
    methods: [POST]
    controller: App\Controller\CalendarController::createEvent

calendar_event_edit:
    path: /calendar/event/{id}/edit
    methods: [POST]
    controller: App\Controller\CalendarController::editEvent

calendar_event_delete:
    path: /calendar/event/{id}/delete
    methods: [POST]
    controller: App\Controller\CalendarController::deleteEvent

# Events
event_create:
    path: /event/create
    methods: [GET, POST]
    controller: App\Controller\EventController::create
event_edit:
    path: /event/{id}/edit
    methods: [GET, POST]
    controller: App\Controller\EventController::edit
event_delete:
    path: /event/{id}/delete
    methods: [POST]
    controller: App\Controller\EventController::delete

# Contacts
contacts:
    path: /contacts
    controller: App\Controller\ContactController::index
create_contact:
    path: /contacts/create
    controller: App\Controller\ContactController::create
edit_contact:
    path: /contacts/{id}/edit
    controller: App\Controller\ContactController::edit
delete_contact:
    path: /contacts/{id}/delete
    controller: App\Controller\ContactController::delete

# Messages
messages:
    path: /messages
    controller: App\Controller\MessageController::index
send_message:
    path: /messages/send
    controller: App\Controller\MessageController::send
